name: zig_fii
description: A minimal Dart project.
version: 0.1.0

environment:
  sdk: ^3.0.0

executables:
  main: main
dependencies:
  ffi: ^2.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  ffigen: ^22.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
