// Emoji data loader. The binary slab is generated by scripts/gen-emoji.zig
// from three vendored JSON files. See src/core/emoji/data/emoji.bin.
//
// File layout (little-endian):
//   Header (16 B)            magic[4] "BMOJ", version u32, count u32, reserved u32
//   String blob (variable)   glyphs, names, joined "name kw1 kw2 ..." text
//   Records (count * 24 B)   u32 glyph_off, u16 glyph_len, u16 _pad
//                            u32 name_off,  u16 name_len,  u16 _pad
//                            u32 kw_off,    u16 kw_len,    u16 _pad
//
// Record offsets are absolute file positions. The blob is laid out in
// the same order as the records (each record's three strings back-to-back
// at the end of the blob).
//
// `loadEmojis` reads the header fields individually, then for each
// record reads its six fields via `std.mem.readInt` (no alignment
// requirement), allocates one `[]EmojiEntry` of size `count`, and fills
// it in. The string slices point at the embedded byte data — no string
// copying, no extra allocations, no `@alignCast` traps.

const std = @import("std");
const entry_mod = @import("entry.zig");

const magic = "BMOJ";
const expected_version: u32 = 1;

// `data` is a plain `[]const u8` — we never cast it to a struct, only
// read individual integer fields from it via `std.mem.readInt`, which
// works on any byte alignment.
const data: []const u8 = @embedFile("data/emoji.bin");

// On-disk byte offsets for the record table.
const header_size: usize = 16;
const record_size: usize = 24;
const glyph_off_off: usize = 0;
const glyph_len_off: usize = 4;
const name_off_off: usize = 8;
const name_len_off: usize = 12;
const kw_off_off: usize = 16;
const kw_len_off: usize = 20;

/// The loaded emoji set. The `entries` slice is allocated and owned by
/// the caller; the per-entry string slices point at the embedded blob.
pub const EmojiData = struct {
    entries: []entry_mod.EmojiEntry,

    pub fn deinit(self: *EmojiData, allocator: std.mem.Allocator) void {
        allocator.free(self.entries);
        self.entries = &.{};
    }
};

/// Loads the embedded emoji slab into a heap-allocated entry slice. Wakes
/// the binary in a single linear sweep — no JSON parsing, no string
/// duplication. The only allocation is the `entries` slice itself.
pub fn loadEmojis(allocator: std.mem.Allocator) !EmojiData {
    if (data.len < header_size) return error.SlabTooSmall;

    // Read the header fields individually (no struct, no alignment).
    if (!std.mem.eql(u8, data[0..4], magic)) return error.BadMagic;
    const version = std.mem.readInt(u32, data[4..8][0..4], .little);
    if (version != expected_version) return error.UnknownVersion;
    const count = std.mem.readInt(u32, data[8..12][0..4], .little);
    if (count == 0) return EmojiData{ .entries = &.{} };
    _ = std.mem.readInt(u32, data[12..16][0..4], .little); // reserved

    const records_bytes_len: usize = count * record_size;
    const records_start: usize = data.len - records_bytes_len;
    if (records_start < header_size) return error.SlabCorrupt;
    if (records_start + records_bytes_len != data.len) return error.SlabCorrupt;

    const entries = try allocator.alloc(entry_mod.EmojiEntry, count);
    errdefer allocator.free(entries);

    for (0..count) |i| {
        const rec = records_start + i * record_size;
        const glyph_off = std.mem.readInt(u32, data[rec + glyph_off_off..][0..4], .little);
        const glyph_len = std.mem.readInt(u16, data[rec + glyph_len_off..][0..2], .little);
        const name_off = std.mem.readInt(u32, data[rec + name_off_off..][0..4], .little);
        const name_len = std.mem.readInt(u16, data[rec + name_len_off..][0..2], .little);
        const kw_off = std.mem.readInt(u32, data[rec + kw_off_off..][0..4], .little);
        const kw_len = std.mem.readInt(u16, data[rec + kw_len_off..][0..2], .little);

        const glyph_end: u32 = glyph_off + glyph_len;
        const name_end: u32 = name_off + name_len;
        const kw_end: u32 = kw_off + kw_len;
        if (glyph_end > records_start or name_end > records_start or kw_end > records_start) {
            return error.OffsetsOutOfRange;
        }
        entries[i] = .{
            .glyph = data[glyph_off..glyph_end],
            .name = data[name_off..name_end],
            .keywords = data[kw_off..kw_end],
        };
    }

    return .{ .entries = entries };
}

test "loadEmojis produces a non-empty set" {
    const allocator = std.testing.allocator;
    var emojis = try loadEmojis(allocator);
    defer emojis.deinit(allocator);
    try std.testing.expect(emojis.entries.len > 1000);
}

test "first entry is the grinning face" {
    const allocator = std.testing.allocator;
    var emojis = try loadEmojis(allocator);
    defer emojis.deinit(allocator);
    try std.testing.expectEqualStrings("😀", emojis.entries[0].glyph);
    try std.testing.expectEqualStrings("grinning face", emojis.entries[0].name);
}

test "keywords field is non-empty and contains the name" {
    const allocator = std.testing.allocator;
    var emojis = try loadEmojis(allocator);
    defer emojis.deinit(allocator);
    const e = emojis.entries[0];
    try std.testing.expect(e.keywords.len > 0);
    try std.testing.expect(std.mem.indexOf(u8, e.keywords, "grinning") != null);
}

test "searching keywords via core.filter finds a match" {
    const allocator = std.testing.allocator;
    var emojis = try loadEmojis(allocator);
    defer emojis.deinit(allocator);

    const query = "rocket";
    const buf = try allocator.alloc(usize, emojis.entries.len);
    defer allocator.free(buf);
    const scratch = try allocator.alloc(@import("../search.zig").ScoredItem, emojis.entries.len);
    defer allocator.free(scratch);
    const n = @import("../filter.zig").filter(
        @import("entry.zig").EmojiEntry,
        @import("entry.zig").searchableOf,
        emojis.entries,
        query,
        buf,
        scratch,
    );
    try std.testing.expect(n > 0);
    // The top result should be the rocket emoji itself.
    try std.testing.expectEqualStrings("🚀", emojis.entries[buf[0]].glyph);
}

test "search keywords match synonyms" {
    const allocator = std.testing.allocator;
    var emojis = try loadEmojis(allocator);
    defer emojis.deinit(allocator);

    // "happy" should match grinning face via emojilib keyword.
    const query = "happy";
    const buf = try allocator.alloc(usize, emojis.entries.len);
    defer allocator.free(buf);
    const scratch = try allocator.alloc(@import("../search.zig").ScoredItem, emojis.entries.len);
    defer allocator.free(scratch);
    const n = @import("../filter.zig").filter(
        @import("entry.zig").EmojiEntry,
        @import("entry.zig").searchableOf,
        emojis.entries,
        query,
        buf,
        scratch,
    );
    try std.testing.expect(n > 0);
    // The smiling face should appear in the top results.
    var found_grin = false;
    for (buf[0..n]) |i| {
        if (std.mem.eql(u8, emojis.entries[i].glyph, "😀")) {
            found_grin = true;
            break;
        }
    }
    try std.testing.expect(found_grin);
}
